In [125]:
import pandas as pd
football = pd.read_csv('Football.csv')

/var/folders/wx/f7_yqkls5vl8cv1w7r38zp1c0000gn/T/ipykernel_18406/2337208304.py:2: DtypeWarning: Columns (0: home_score, 1: away_score, 2: home_team_goals_current_time, 3: home_team_goals_current_score, 4: home_team_goals, 5: home_team_goals_assist, 6: away_team_goals_current_time, 7: away_team_goals_current_score, 8: away_team_goals, 9: away_team_goals_assist, 10: home_team_yellow_card_current_time, 11: home_team_yellow_card, 12: home_team_yellow_card_why, 13: away_team_yellow_card_current_time, 14: away_team_yellow_card, 15: away_team_yellow_card_why, 16: home_team_red_card_current_time, 17: home_team_red_card, 18: home_team_red_card_why, 19: away_team_red_card_current_time, 20: away_team_red_card, 21: away_team_red_card_why, 22: home_team_substitutions_current_time, 23: home_team_substitutions, 24: home_team_substitutions_with, 25: home_team_substitution_why, 26: away_team_substitutions_current_time, 27: away_team_substitutions, 28: away_team_substitutions_with, 29: away_team_substitution_why, 30: Tackles_Home, 31: Tackles_Host) have mixed types. Specify dtype option on import or set low_memory=False.
  football = pd.read_csv('Football.csv')

In [126]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95384 entries, 0 to 95383
Data columns (total 91 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Country                               95384 non-null  str
 1   League                                95384 non-null  str
 2   home_team                             95384 non-null  str
 3   away_team                             95384 non-null  str
 4   home_score                            95384 non-null  object
 5   away_score                            95384 non-null  object
 6   season_year                           95384 non-null  str
 7   Date_day                              95384 non-null  float64
 8   Date_hour                             95384 non-null  str
 9   first_half                            95125 non-null  str
 10  second_half                           77509 non-null  str
 11  home_team_goals_current_time          26471 non-null  str
 12  home_team_goals_current_score         26391 non-null  str
 13  home_team_goals                       23105 non-null  str
 14  home_team_goals_assist                23105 non-null  str
 15  away_team_goals_current_time          23134 non-null  str
 16  away_team_goals_current_score         23077 non-null  str
 17  away_team_goals                       20534 non-null  str
 18  away_team_goals_assist                20534 non-null  str
 19  home_team_yellow_card_current_time    26509 non-null  str
 20  home_team_yellow_card                 26477 non-null  str
 21  home_team_yellow_card_why             12220 non-null  str
 22  away_team_yellow_card_current_time    30695 non-null  str
 23  away_team_yellow_card                 30675 non-null  str
 24  away_team_yellow_card_why             12842 non-null  str
 25  home_team_red_card_current_time       1764 non-null   str
 26  home_team_red_card                    1758 non-null   str
 27  home_team_red_card_why                1172 non-null   str
 28  away_team_red_card_current_time       2103 non-null   str
 29  away_team_red_card                    2091 non-null   str
 30  away_team_red_card_why                1402 non-null   str
 31  home_team_substitutions_current_time  20903 non-null  str
 32  home_team_substitutions               20902 non-null  str
 33  home_team_substitutions_with          20902 non-null  str
 34  home_team_substitution_why            20902 non-null  str
 35  away_team_substitutions_current_time  20896 non-null  str
 36  away_team_substitutions               20894 non-null  str
 37  away_team_substitutions_with          20894 non-null  str
 38  away_team_substitution_why            20894 non-null  str
 39  expected_goals_xg_home                5081 non-null   float64
 40  expected_goals_xg_host                5081 non-null   float64
 41  Ball_Possession_Home                  37721 non-null  str
 42  Ball_Possession_Host                  37721 non-null  str
 43  Goal_Attempts_Home                    38453 non-null  float64
 44  Goal_Attempts_Host                    38453 non-null  float64
 45  Shots_on_Goal_Home                    38449 non-null  float64
 46  Shots_on_Goal_Host                    38449 non-null  float64
 47  Shots_off_Goal_Home                   38390 non-null  float64
 48  Shots_off_Goal_Host                   38390 non-null  float64
 49  Blocked_Shots_Home                    27003 non-null  float64
 50  Blocked_Shots_Host                    27003 non-null  float64
 51  Free_Kicks_Home                       29769 non-null  float64
 52  Free_Kicks_Host                       29769 non-null  float64
 53  Corner_Kicks_Home                     38394 non-null  float64
 54  Corner_Kicks_Host                     38394 non-null  float64
 55  Offsides_Home                         36732 non-null  float64
 56  Offsides_Host                         36732 non-null  float64
 57  Throw_ins_Home                        19125 non-null  float64
 58  Throw_ins_Host                        19125 non-null  float64
 59  Goalkeeper_Saves_Home                 38453 non-null  float64
 60  Goalkeeper_Saves_Host                 38453 non-null  float64
 61  Fouls_Home                            35873 non-null  float64
 62  Fouls_Host                            35873 non-null  float64
 63  Red_Cards_Home                        7072 non-null   float64
 64  Red_Cards_Host                        7072 non-null   float64
 65  Yellow_Cards_Home                     37635 non-null  float64
 66  Yellow_Cards_Host                     37635 non-null  float64
 67  Total_Passes_Home                     11649 non-null  float64
 68  Total_Passes_Host                     11649 non-null  float64
 69  Completed_Passes_Home                 6568 non-null   float64
 70  Completed_Passes_Host                 6568 non-null   float64
 71  Tackles_Home                          8343 non-null   object
 72  Tackles_Host                          8343 non-null   object
 73  Crosses_Completed_Home                382 non-null    float64
 74  Crosses_Completed_Host                382 non-null    float64
 75  Interceptions_Home                    864 non-null    float64
 76  Interceptions_Host                    864 non-null    float64
 77  Attacks_Home                          13512 non-null  float64
 78  Attacks_Host                          13512 non-null  float64
 79  Dangerous_Attacks_Home                13513 non-null  float64
 80  Dangerous_Attacks_Host                13513 non-null  float64
 81  Distance_Covered_(km)_Home            549 non-null    float64
 82  Distance_Covered_(km)_Host            549 non-null    float64
 83  Clearances_Completed_Home             588 non-null    float64
 84  Clearances_Completed_Host             588 non-null    float64
 85  Pass_Success_per_Home                 13 non-null     float64
 86  Pass_Success_per_Host                 13 non-null     float64
 87  referee                               42908 non-null  str
 88  venue                                 69556 non-null  str
 89  capacity                              69551 non-null  str
 90  attendance                            30794 non-null  str
dtypes: float64(45), object(4), str(42)
memory usage: 66.2+ MB

In [127]:
df.head(10)

,Country,League,home_team,away_team,home_score,away_score,season_year,Date_day,Date_hour,first_half,...,Distance_Covered_(km)_Home,Distance_Covered_(km)_Host,Clearances_Completed_Home,Clearances_Completed_Host,Pass_Success_per_Home,Pass_Success_per_Host,referee,venue,capacity,attendance
0,Germany,Bundesliga,B. Monchengladbach,Werder Bremen,4,1,2024/2025,3.11,19:30,3 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Dankert B. (Ger),Borussia-Park (Mönchengladbach),54 042,54 042
1,Germany,Bundesliga,Freiburg,Mainz,0,0,2024/2025,3.11,17:30,0 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Brand B. (Ger),Europa-Park Stadion (Freiburg),34 700,34 400
2,Germany,Bundesliga,Dortmund,RB Leipzig,2,1,2024/2025,2.11,20:30,1 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Stieler T. (Ger),Signal Iduna Park (Dortmund),81 365,81 365
3,Germany,Bundesliga,Bayern Munich,Union Berlin,3,0,2024/2025,2.11,17:30,2 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Jollenbeck M. (Ger),Allianz Arena (Munich),75 024,75 000
4,Germany,Bundesliga,Eintracht Frankfurt,Bochum,7,2,2024/2025,2.11,17:30,4 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Schlager D. (Ger),Deutsche Bank Park (Frankfurt),58 000,58 000
5,Germany,Bundesliga,Hoffenheim,St. Pauli,0,2,2024/2025,2.11,17:30,0 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Stegemann S. (Ger),PreZero Arena (Sinsheim),30 150,26 199
6,Germany,Bundesliga,Holstein Kiel,Heidenheim,1,0,2024/2025,2.11,17:30,1 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Willenborg F. (Ger),Holstein-Stadion (Kiel),15 034,14 000
7,Germany,Bundesliga,Wolfsburg,Augsburg,1,1,2024/2025,2.11,17:30,0 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Brych F. (Ger),Volkswagen Arena (Wolfsburg),28 917,25 000
8,Germany,Bundesliga,Bayer Leverkusen,Stuttgart,0,0,2024/2025,1.11,22:30,0 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Siebert D. (Ger),BayArena (Leverkusen),30 210,30 210
9,Germany,Bundesliga,Heidenheim,Hoffenheim,0,0,2024/2025,27.10,21:30,0 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Dingert C. (Ger),Voith-Arena (Heidenheim),15 000,15 000

In [128]:
df.describe(include='all')

,Country,League,home_team,away_team,home_score,away_score,season_year,Date_day,Date_hour,first_half,...,Distance_Covered_(km)_Home,Distance_Covered_(km)_Host,Clearances_Completed_Home,Clearances_Completed_Host,Pass_Success_per_Home,Pass_Success_per_Host,referee,venue,capacity,attendance
count,95384,95384,95384,95384,95384.0,95384.0,95384,95384.000000,95384,95125,...,549.000000,549.000000,588.000000,588.000000,13.000000,13.000000,42908,69556,69551,30794
unique,6,18,2518,2141,26.0,26.0,25,NaN,125,69,...,NaN,NaN,NaN,NaN,NaN,NaN,696,657,533,20020
top,England,Championship,Juventus,Sampdoria,1.0,1.0,2021/2022,NaN,17:00,0 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Taylor A. (Eng),Stadio Olimpico (Rome),70 634,50 000
freq,26107,9854,517,502,25778.0,27462.0,4354,NaN,16564,25457,...,NaN,NaN,NaN,NaN,NaN,NaN,427,950,950,156
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.621889,NaN,NaN,...,116.795993,116.519126,17.394558,21.292517,47.384615,49.923077,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.773724,NaN,NaN,...,9.809048,9.878371,8.245846,9.208515,39.301269,41.357106,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.010000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.040000,NaN,NaN,...,114.000000,114.000000,12.000000,14.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.030000,NaN,NaN,...,118.000000,117.000000,17.000000,20.000000,73.000000,75.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.040000,NaN,NaN,...,121.000000,121.000000,22.000000,27.000000,77.000000,83.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.120000,NaN,NaN,...,151.000000,151.000000,49.000000,63.000000,83.000000,90.000000,NaN,NaN,NaN,NaN

In [129]:
# summarize frequency of counts of data in categories
for c in ['Country', 'League', 'home_team', 'away_team', 'season_year']:
    print(football[c].value_counts(dropna=False).head(5))

Country
England    26107
Italy      20481
France     20385
Germany    16326
Turkey      6569
Name: count, dtype: int64
League
Championship      9854
Serie-b           9668
Premier-league    9220
Ligue-2           9158
Serie-a           8990
Name: count, dtype: int64
home_team
Juventus     517
Inter        513
AC Milan     509
Sampdoria    508
AS Roma      506
Name: count, dtype: int64
away_team
Sampdoria         502
Lazio             496
Juventus          496
Inter             496
Manchester Utd    495
Name: count, dtype: int64
season_year
2021/2022    4354
2022/2023    4337
2014/2015    4310
2017/2018    4309
2016/2017    4289
Name: count, dtype: int64

In [130]:
# how many rows are in the data set?
print(len(football))

95384

In [131]:
# how many unique order_id's are in the data? 
print(football[['Country', 'League', 'home_team', 'away_team', 'Date_day']].nunique())

Country         6
League         18
home_team    2518
away_team    2141
Date_day      365
dtype: int64

In [132]:
# how many unique rows in the data?
print(len(football.drop_duplicates()))

95384

2. Data Types and Special Characters

In [133]:
football[['home_score', 'away_score']].dtypes

home_score    object
away_score    object
dtype: object

In [134]:
football['home_score'].value_counts(dropna=False)

home_score
1     25778
2     19252
0     18466
3      9853
1      5386
2      3962
0      3896
4      3852
3      1884
5      1238
4       818
6       399
5       261
6       113
7       102
8        37
7        37
9        16
8        12
-         9
10        5
9         3
10        2
12        1
14        1
15        1
Name: count, dtype: int64

scores columns aren't fully numeric which is why python can't sum them

In [135]:
football['away_score'].value_counts(dropna=False)

away_score
1     27462
0     25396
2     15972
3      6830
1      5620
0      5312
2      3289
4      2260
3      1383
5       696
4       502
6       245
5       179
7        82
6        59
7        26
8        22
9        22
-         9
10        6
11        3
8         3
12        2
9         2
15        1
14        1
Name: count, dtype: int64

In [136]:
football['home_score'] = pd.to_numeric(
    football['home_score'], errors='coerce'
)

football['away_score'] = pd.to_numeric(
    football['away_score'], errors='coerce'
)

In [137]:
football[['home_score', 'away_score']].isna().sum()

home_score    9
away_score    9
dtype: int64

In [138]:
# total goals using all rows
total_goals = (
    football['home_score'].sum()
    + football['away_score'].sum()
)

print(total_goals)

258505.0

In [139]:
# remove completely identical rows
football_no_dupes = football.drop_duplicates()

# total goals after removing identical rows
total_goals_no_dupes = (
    football_no_dupes['home_score'].sum()
    + football_no_dupes['away_score'].sum()
)

print(total_goals_no_dupes)

258505.0

In [140]:
print(len(football))
print(len(football_no_dupes))

95384
95384

In [141]:
# count unique matches

match_key = [
    'Country',
    'League',
    'home_team',
    'away_team',
    'Date_day'
]

football_unique_matches = football.drop_duplicates(subset=match_key)

print(len(football))
print(len(football_unique_matches))

95384
94339

In [142]:
football[['Date_day', 'season_year']].head(20)

    Date_day season_year
0       3.11   2024/2025
1       3.11   2024/2025
2       2.11   2024/2025
3       2.11   2024/2025
4       2.11   2024/2025
5       2.11   2024/2025
6       2.11   2024/2025
7       2.11   2024/2025
8       1.11   2024/2025
9      27.10   2024/2025
10     27.10   2024/2025
11     27.10   2024/2025
12     26.10   2024/2025
13     26.10   2024/2025
14     26.10   2024/2025
15     26.10   2024/2025
16     26.10   2024/2025
17     25.10   2024/2025
18     20.10   2024/2025
19     20.10   2024/2025

In [143]:
match_key = [
    'Country',
    'League',
    'season_year',
    'home_team',
    'away_team',
    'Date_day'
]

football_unique_matches = football.drop_duplicates(subset=match_key)

print(len(football))
print(len(football_unique_matches))

95384
95345

In [144]:
# find all rows that share the same match key
dupe_mask = football.duplicated(
    subset=match_key,
    keep=False
)

duplicate_rows = (
    football.loc[dupe_mask]
    .sort_values(match_key)
)

duplicate_rows

,Country,League,home_team,away_team,home_score,away_score,season_year,Date_day,Date_hour,first_half,...,Distance_Covered_(km)_Home,Distance_Covered_(km)_Host,Clearances_Completed_Home,Clearances_Completed_Host,Pass_Success_per_Home,Pass_Success_per_Host,referee,venue,capacity,attendance
55206,England,Championship,Norwich,Walsall,1.0,1.0,2001/2002,1.01,17:00,1 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55584,England,Championship,Norwich,Walsall,1.0,1.0,2001/2002,1.01,17:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48544,England,Championship,Ipswich,Aston Villa,0.0,4.0,2017/2018,21.04,17:00,0 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hooper S. (Eng),Portman Road (Ipswich),29 673,20 034
48831,England,Championship,Ipswich,Aston Villa,0.0,4.0,2017/2018,21.04,17:00,0 - 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hooper S. (Eng),Portman Road (Ipswich),30 017,20 034
48568,England,Championship,Ipswich,Barnsley,1.0,0.0,2017/2018,10.04,21:45,0 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Linington J. (Eng),Portman Road (Ipswich),29 673,13 271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81481,Italy,Coppa-italia,Atalanta,Cesena,6.0,1.0,2024/2025,18.12,20:30,4 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81476,Italy,Coppa-italia,Inter,Udinese,2.0,0.0,2024/2025,19.12,23:00,1ST HALF,...,NaN,NaN,NaN,NaN,NaN,NaN,Massimi L. (Ita),Stadio Giuseppe Meazza (San Siro) (Milan),80 018,53 576
81480,Italy,Coppa-italia,Inter,Udinese,2.0,0.0,2024/2025,19.12,23:00,2 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,Massimi L. (Ita),Stadio Giuseppe Meazza (San Siro) (Milan),80 018,53 576
81479,Italy,Coppa-italia,Juventus,Cagliari,4.0,0.0,2024/2025,17.12,23:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81482,Italy,Coppa-italia,Juventus,Cagliari,4.0,0.0,2024/2025,17.12,23:00,1 - 0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
# count missing values in each duplicate row
duplicate_rows['missing_values'] = duplicate_rows.isna().sum(axis=1)

duplicate_rows[
    match_key + ['missing_values']
].head(20)

,Country,League,season_year,home_team,away_team,Date_day,missing_values
55206,England,Championship,2001/2002,Norwich,Walsall,1.01,81
55584,England,Championship,2001/2002,Norwich,Walsall,1.01,82
48544,England,Championship,2017/2018,Ipswich,Aston Villa,21.04,44
48831,England,Championship,2017/2018,Ipswich,Aston Villa,21.04,44
48568,England,Championship,2017/2018,Ipswich,Barnsley,10.04,36
48832,England,Championship,2017/2018,Ipswich,Barnsley,10.04,36
48698,England,Championship,2017/2018,Ipswich,Burton,10.02,48
48837,England,Championship,2017/2018,Ipswich,Burton,10.02,48
48672,England,Championship,2017/2018,Ipswich,Cardiff,21.02,36
48836,England,Championship,2017/2018,Ipswich,Cardiff,21.02,36
48770,England,Championship,2017/2018,Ipswich,Derby,30.12,44
48840,England,Championship,2017/2018,Ipswich,Derby,30.12,44
48623,England,Championship,2017/2018,Ipswich,Hull,13.03,44
48834,England,Championship,2017/2018,Ipswich,Hull,13.03,44
48747,England,Championship,2017/2018,Ipswich,Leeds,13.01,42
48839,England,Championship,2017/2018,Ipswich,Leeds,13.01,42
48518,England,Championship,2017/2018,Ipswich,Middlesbrough,6.05,44
48830,England,Championship,2017/2018,Ipswich,Middlesbrough,6.05,44
48593,England,Championship,2017/2018,Ipswich,Millwall,2.04,36
48833,England,Championship,2017/2018,Ipswich,Millwall,2.04,36

In [146]:
# compare one duplicated match
football.loc[
    [48544, 48831]
].T
row1 = football.loc[48544]
row2 = football.loc[48831]

different = (
    (row1 != row2)
    & ~(row1.isna() & row2.isna())
)

pd.DataFrame({
    'row_48544': row1[different],
    'row_48831': row2[different]
})

         row_48544 row_48831
capacity    29 673    30 017

In [147]:
# count missing values in each row
football['missing_values'] = football.isna().sum(axis=1)

# put the most complete version of each match first
football = football.sort_values('missing_values')

# keep one row per match
football = football.drop_duplicates(
    subset=match_key,
    keep='first'
)

# remove the temporary missing-values column
football = football.drop(columns='missing_values')

print(len(football))

95345

3. Categories that look identical

In [148]:
# look at the values in Country
print(football['Country'].value_counts())

Country
England    26074
Italy      20478
France     20382
Germany    16326
Turkey      6569
Spain       5516
Name: count, dtype: int64

In [149]:
# show the exact unique values in Country
print([repr(s) for s in football['Country'].unique()])

["'France'", "'England'", "'Germany'", "'Italy'", "'Spain'", "'Turkey'"]

In [150]:
# look at the values in League
print(football['League'].value_counts())

# show the exact unique values in League
print([repr(s) for s in football['League'].unique()])

League
Championship            9824
Serie-b                 9668
Premier-league          9220
Ligue-2                 9156
Serie-a                 8990
2-bundesliga            7479
Bundesliga              7304
Fa-cup                  7030
Ligue-1                 6887
Coupe-de-france         4339
Laliga2                 2607
Laliga                  2583
1-lig                   2529
Super-lig               2449
Coppa-italia            1820
2-lig-white-group       1591
Dfb-pokal               1543
Primera-rfef-group-1     326
Name: count, dtype: int64
["'Ligue-1'", "'Fa-cup'", "'Bundesliga'", "'Premier-league'", "'2-bundesliga'", "'Championship'", "'Dfb-pokal'", "'Serie-a'", "'Coupe-de-france'", "'Coppa-italia'", "'Ligue-2'", "'Serie-b'", "'Laliga'", "'Laliga2'", "'Super-lig'", "'1-lig'", "'2-lig-white-group'", "'Primera-rfef-group-1'"]

In [151]:
# check for extra spaces in home team names
print(
    (football['home_team'] != football['home_team'].str.strip()).sum()
)

0

In [152]:
# check for extra spaces in away team names
print(
    (football['away_team'] != football['away_team'].str.strip()).sum()
)

0

4. Impossible Values

In [158]:
football.columns.tolist()

football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].dtypes

football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].head(10)

,Ball_Possession_Home,Ball_Possession_Host,Goal_Attempts_Home,Goal_Attempts_Host
16487,52%,48%,16.0,22.0
16465,63%,37%,15.0,5.0
16630,62%,38%,32.0,5.0
16558,46%,54%,7.0,16.0
16513,40%,60%,9.0,14.0
16608,38%,62%,9.0,13.0
16514,52%,48%,23.0,11.0
16617,46%,54%,15.0,12.0
16435,33%,67%,12.0,33.0
16540,51%,49%,17.0,16.0

In [ ]:
football['Ball_Possession_Home'] = pd.to_numeric(
    football['Ball_Possession_Home'].str.replace('%', ''),
    errors='coerce'
)

football['Ball_Possession_Host'] = pd.to_numeric(
    football['Ball_Possession_Host'].str.replace('%', ''),
    errors='coerce'
)

AttributeError: Can only use .str accessor with string values, not floating

In [161]:
football[
    ['Ball_Possession_Home', 'Ball_Possession_Host']
].dtypes

Ball_Possession_Home    float64
Ball_Possession_Host    float64
dtype: object

In [162]:
football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].describe()

,Ball_Possession_Home,Ball_Possession_Host,Goal_Attempts_Home,Goal_Attempts_Host
count,37684.000000,37684.000000,38416.000000,38416.000000
mean,51.080671,48.919595,13.219492,11.047636
std,9.827851,9.827823,5.172720,4.717016
min,1.000000,10.000000,0.000000,0.000000
25%,45.000000,42.000000,10.000000,8.000000
50%,51.000000,49.000000,13.000000,11.000000
75%,58.000000,55.000000,16.000000,14.000000
max,90.000000,99.000000,46.000000,41.000000

In [163]:
football['total_possession'] = (
    football['Ball_Possession_Home']
    + football['Ball_Possession_Host']
)

football['total_possession'].value_counts().sort_index()

total_possession
100.0    37674
101.0       10
Name: count, dtype: int64

In [164]:
football = football.drop(columns='total_possession')

5. Missing-not-at-random

In [168]:
football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].isna().sum()

football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].isna().mean().round(3)

Ball_Possession_Home    0.605
Ball_Possession_Host    0.605
Goal_Attempts_Home      0.597
Goal_Attempts_Host      0.597
dtype: float64

In [169]:
print(
    football.groupby('season_year')['Ball_Possession_Home']
    .apply(lambda x: x.isna().mean())
)

season_year
2000/2001    1.000000
2001/2002    1.000000
2002/2003    1.000000
2003/2004    1.000000
2004/2005    1.000000
2005/2006    1.000000
2006/2007    1.000000
2007/2008    1.000000
2008/2009    1.000000
2009/2010    1.000000
2010/2011    0.998946
2011/2012    0.996015
2012/2013    0.938565
2013/2014    0.328515
2014/2015    0.321578
2015/2016    0.252802
2016/2017    0.206953
2017/2018    0.182030
2018/2019    0.257351
2019/2020    0.239606
2020/2021    0.148839
2021/2022    0.177079
2022/2023    0.181734
2023/2024    0.177585
2024/2025    0.314356
Name: Ball_Possession_Home, dtype: float64

In [170]:
print(
    football.groupby('season_year')['Goal_Attempts_Home']
    .apply(lambda x: x.isna().mean())
)

season_year
2000/2001    1.000000
2001/2002    1.000000
2002/2003    1.000000
2003/2004    1.000000
2004/2005    1.000000
2005/2006    1.000000
2006/2007    1.000000
2007/2008    1.000000
2008/2009    1.000000
2009/2010    1.000000
2010/2011    0.998946
2011/2012    0.996015
2012/2013    0.924406
2013/2014    0.325950
2014/2015    0.318097
2015/2016    0.252564
2016/2017    0.206953
2017/2018    0.174581
2018/2019    0.178311
2019/2020    0.171464
2020/2021    0.148839
2021/2022    0.177079
2022/2023    0.181734
2023/2024    0.177585
2024/2025    0.313738
Name: Goal_Attempts_Home, dtype: float64

In [171]:
print(
    football.groupby('League')['Ball_Possession_Home']
    .apply(lambda x: x.isna().mean())
    .sort_values()
)

League
Ligue-1                 0.399593
Championship            0.509976
Serie-a                 0.516908
Bundesliga              0.524096
2-bundesliga            0.533093
Premier-league          0.535249
Laliga                  0.548200
Laliga2                 0.560031
Super-lig               0.576970
Serie-b                 0.604055
Dfb-pokal               0.627997
Ligue-2                 0.638925
1-lig                   0.720047
Coppa-italia            0.808791
Fa-cup                  0.901849
Coupe-de-france         0.922793
Primera-rfef-group-1    1.000000
2-lig-white-group       1.000000
Name: Ball_Possession_Home, dtype: float64

6. Cardinality and Table Joins

In [172]:
print(len(football))

print(
    football.duplicated(
        subset=match_key
    ).sum()
)

95345
0

Deciding which seasons are usable

In [174]:
major_leagues = [
    'Premier-league',
    'Laliga',
    'Serie-a',
    'Bundesliga',
    'Ligue-1'
]

In [175]:
major_football = football[
    football['League'].isin(major_leagues)
]

print(len(major_football))

34984

In [176]:
major_football = major_football.copy()

major_football['usable'] = (
    major_football['Ball_Possession_Home'].notna()
    & major_football['Ball_Possession_Host'].notna()
    & major_football['Goal_Attempts_Home'].notna()
    & major_football['Goal_Attempts_Host'].notna()
)

print(
    major_football.groupby('season_year')['usable']
    .mean()
    .round(3)
)

season_year
2000/2001    0.000
2001/2002    0.000
2002/2003    0.000
2003/2004    0.000
2004/2005    0.000
2005/2006    0.000
2006/2007    0.000
2007/2008    0.000
2008/2009    0.000
2009/2010    0.000
2010/2011    0.003
2011/2012    0.013
2012/2013    0.000
2013/2014    0.999
2014/2015    1.000
2015/2016    1.000
2016/2017    1.000
2017/2018    1.000
2018/2019    1.000
2019/2020    1.000
2020/2021    0.999
2021/2022    1.000
2022/2023    0.999
2023/2024    0.999
2024/2025    1.000
Name: usable, dtype: float64

In [177]:
analysis_football = football[
    (football['League'].isin(major_leagues))
    & (football['season_year'] >= '2013/2014')
].copy()

print(len(analysis_football))

17392

In [178]:
analysis_football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host',
        'home_score',
        'away_score'
    ]
].isna().sum()

Ball_Possession_Home    4
Ball_Possession_Host    4
Goal_Attempts_Home      4
Goal_Attempts_Host      4
home_score              0
away_score              0
dtype: int64

In [180]:
analysis_football = analysis_football.dropna(
    subset=[
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host',
        'home_score',
        'away_score'
    ]
)

print(len(analysis_football))

17388

In [ ]:
football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].isna().sum()

football[
    [
        'Ball_Possession_Home',
        'Ball_Possession_Host',
        'Goal_Attempts_Home',
        'Goal_Attempts_Host'
    ]
].isna().mean().round(3)

Ball_Possession_Home    0.605
Ball_Possession_Host    0.605
Goal_Attempts_Home      0.597
Goal_Attempts_Host      0.597
dtype: float64

In [181]:
print(
    (analysis_football['Goal_Attempts_Home'] == 0).sum()
)

print(
    (analysis_football['Goal_Attempts_Host'] == 0).sum()
)

2
11

In [183]:
import numpy as np

analysis_football['home_attacking_efficiency'] = np.where(
    analysis_football['Goal_Attempts_Home'] > 0,
    analysis_football['home_score'] / analysis_football['Goal_Attempts_Home'],
    np.nan
)

analysis_football['away_attacking_efficiency'] = np.where(
    analysis_football['Goal_Attempts_Host'] > 0,
    analysis_football['away_score'] / analysis_football['Goal_Attempts_Host'],
    np.nan
)

In [184]:
analysis_football[
    [
        'home_attacking_efficiency',
        'away_attacking_efficiency'
    ]
].describe()

       home_attacking_efficiency  away_attacking_efficiency
count               17386.000000               17377.000000
mean                    0.120087                   0.116012
std                     0.105438                   0.116061
min                     0.000000                   0.000000
25%                     0.047619                   0.000000
50%                     0.105263                   0.100000
75%                     0.176471                   0.176471
max                     1.000000                   1.000000

In [185]:
print("Rows:", len(analysis_football))

print("Duplicate matches:", analysis_football.duplicated(
    subset=match_key
).sum())

print("\nMissing analysis values:")
print(
    analysis_football[
        [
            'Ball_Possession_Home',
            'Ball_Possession_Host',
            'Goal_Attempts_Home',
            'Goal_Attempts_Host',
            'home_score',
            'away_score'
        ]
    ].isna().sum()
)

print("\nLeagues:")
print(analysis_football['League'].value_counts())

print("\nSeasons:")
print(analysis_football['season_year'].value_counts().sort_index())

Rows: 17388
Duplicate matches: 0

Missing analysis values:
Ball_Possession_Home    0
Ball_Possession_Host    0
Goal_Attempts_Home      0
Goal_Attempts_Host      0
home_score              0
away_score              0
dtype: int64

Leagues:
League
Serie-a           4338
Premier-league    4280
Ligue-1           4135
Bundesliga        3468
Laliga            1167
Name: count, dtype: int64

Seasons:
season_year
2013/2014    1551
2014/2015    1555
2015/2016    1554
2016/2017    1556
2017/2018    1557
2018/2019    1561
2019/2020    1454
2020/2021    1560
2021/2022    1558
2022/2023    1553
2023/2024    1483
2024/2025     446
Name: count, dtype: int64

In [186]:
print(
    analysis_football.groupby(
        ['season_year', 'League']
    ).size().unstack(fill_value=0)
)

League       Bundesliga  Laliga  Ligue-1  Premier-league  Serie-a
season_year
2013/2014           308     103      380             380      380
2014/2015           308     107      380             380      380
2015/2016           308     106      380             380      380
2016/2017           308     106      382             380      380
2017/2018           308     105      384             380      380
2018/2019           308     109      384             380      380
2019/2020           308     107      279             380      380
2020/2021           308     108      384             380      380
2021/2022           308     106      384             380      380
2022/2023           307     105      380             380      381
2023/2024           308     105      310             380      380
2024/2025            81       0      108             100      157

In [187]:
football[
    football['Country'] == 'Spain'
]['League'].value_counts()

League
Laliga2                 2607
Laliga                  2583
Primera-rfef-group-1     326
Name: count, dtype: int64

In [188]:
analysis_football = analysis_football[
    analysis_football['season_year'] != '2024/2025'
].copy()

print(len(analysis_football))

print(
    analysis_football.groupby(
        ['season_year', 'League']
    ).size().unstack(fill_value=0)
)

16942
League       Bundesliga  Laliga  Ligue-1  Premier-league  Serie-a
season_year
2013/2014           308     103      380             380      380
2014/2015           308     107      380             380      380
2015/2016           308     106      380             380      380
2016/2017           308     106      382             380      380
2017/2018           308     105      384             380      380
2018/2019           308     109      384             380      380
2019/2020           308     107      279             380      380
2020/2021           308     108      384             380      380
2021/2022           308     106      384             380      380
2022/2023           307     105      380             380      381
2023/2024           308     105      310             380      380

Before cheking the data, I checked for duplicates, missing values, bad formatting, and impossible values. I found duplicate records respresenting the same match and removed them. I also converted qunatitiatvie columns to numeric formats. 

The reason I chose this data set was because of how vast the informaition spanned. Unfortunately, a large amount of possesion and goal-attempt data was missing in the eariler seasons. It seems that these statistics were only accessible around 2013. There was also not enough information during the 24/25 season in Spain, so I removed that. Additionally, there were 18 leagues across 6 countries, but with limited data in the smaller leagues, I decided to take only 5 top flight leagues for this analysis. Matches missing variables required for my analysis were also removed. 

Finally, I defined new variables for both the home and away teams by dividing goals by total goal attempts. These columns will serve as the driver for my analysis.

In [191]:
football.columns
football['Country'].value_counts()

Country
England    26074
Italy      20478
France     20382
Germany    16326
Turkey      6569
Spain       5516
Name: count, dtype: int64